### ISSUE TITLE
Any plans to upstream your fork of Pluto?

### ISSUE THREAD

**Issue by VarLad** [disberd/PlutoDevMacros.jl#1]

**Comment by disberd** [comment]
The main added functionality of notebook exclusive cells will become very easy to implement when [this pr](https://github.com/fonsp/Pluto.jl/pull/1895) is merged (which should happen relatively soon).
I still have some minor quirks in my own pluto fork for my own convenience that won't probably be accepted as PR, but the notebook exclusive cells should be possible

**Comment by VarLad** [comment]
Since the PR has merged, any update on getting this to run on normal Pluto :)

**Comment by disberd** [comment]
I'll try to adapt the code to the new metadata in the next days and submit a PR to Pluto :).
It'll probably take a while to get polished and approved while there though.

**Comment by disberd** [comment]
Draft PR created:
https://github.com/fonsp/Pluto.jl/pull/2018

**Comment by disberd** [comment]
https://github.com/fonsp/Pluto.jl/pull/2018 has been merged, so I am going to close this issue!
